# Generated by Codex on 2026-05-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mapasset',
            name='asset_type',
            field=models.CharField(
                choices=[
                    ('practice', 'Practice map'),
                    ('toposheet', 'Toposheet'),
                    ('outline', 'Outline map'),
                    ('custom', 'Custom'),
                ],
                default='practice',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='mapasset',
            name='default_calibration_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mapasset',
            name='default_project_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mapasset',
            name='grade_level',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='MapProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('custom_map_image', models.ImageField(blank=True, upload_to='geography/project_maps/')),
                ('project_json', models.JSONField(blank=True, default=dict)),
                ('calibration_json', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('in_review', 'In review'),
                            ('completed', 'Completed'),
                            ('archived', 'Archived'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'map_asset',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='projects',
                        to='geography.mapasset',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='geography_map_projects',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'scenario',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='map_projects',
                        to='simulations.scenario',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='map_projects',
                        to='simulations.simulationsession',
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='map_projects',
                        to='geography.geographytask',
                    ),
                ),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MapFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                (
                    'feature_type',
                    models.CharField(
                        choices=[
                            ('point', 'Point'),
                            ('line', 'Line'),
                            ('polygon', 'Polygon'),
                            ('label', 'Label'),
                            ('measure', 'Measure'),
                        ],
                        default='point',
                        max_length=30,
                    ),
                ),
                ('category', models.CharField(blank=True, max_length=80)),
                ('icse_force', models.CharField(blank=True, max_length=80)),
                ('geometry', models.JSONField(blank=True, default=dict)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('importance_notes', models.TextField(blank=True)),
                ('exam_notes', models.TextField(blank=True)),
                ('social_studies_notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='features',
                        to='geography.mapproject',
                    ),
                ),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeographyAIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('explain_feature', 'Explain feature'),
                            ('generate_questions', 'Generate questions'),
                            ('check_project', 'Check project'),
                            ('revision_sheet', 'Revision sheet'),
                        ],
                        max_length=40,
                    ),
                ),
                ('input_json', models.JSONField(blank=True, default=dict)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('questions_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'feature',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='ai_interactions',
                        to='geography.mapfeature',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ai_interactions',
                        to='geography.mapproject',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='geography_ai_interactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapFeatureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'note_type',
                    models.CharField(
                        choices=[
                            ('general', 'General'),
                            ('importance', 'Importance'),
                            ('exam', 'Exam'),
                            ('social_studies', 'Social studies'),
                        ],
                        default='general',
                        max_length=30,
                    ),
                ),
                ('body', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='geography_feature_notes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'feature',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notes',
                        to='geography.mapfeature',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapFeaturePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='geography/feature_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'feature',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='geography.mapfeature',
                    ),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='geography_feature_photos',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mapsubmission',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='submissions',
                to='geography.mapproject',
            ),
        ),
    ]
