# Generated by Codex on 2026-05-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_geography_map_lab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographyaiinteraction',
            name='action',
            field=models.CharField(
                choices=[
                    ('explain_feature', 'Explain feature'),
                    ('generate_questions', 'Generate questions'),
                    ('generate_feature_json', 'Generate feature JSON'),
                    ('chat', 'Chat'),
                    ('study_notes', 'Study notes'),
                    ('public_context', 'Public context'),
                    ('check_project', 'Check project'),
                    ('revision_sheet', 'Revision sheet'),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name='GeographyChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                (
                    'scope',
                    models.CharField(
                        choices=[('feature', 'Feature'), ('project', 'Project'), ('general', 'General')],
                        default='feature',
                        max_length=20,
                    ),
                ),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'feature',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='chat_sessions',
                        to='geography.mapfeature',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chat_sessions',
                        to='geography.mapproject',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='geography_chat_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeographyChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('user', 'User'),
                            ('assistant', 'Assistant'),
                            ('system', 'System'),
                            ('tool', 'Tool'),
                        ],
                        max_length=20,
                    ),
                ),
                ('content', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'chat_session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='geography.geographychatsession',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GeographyStudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('notes_text', models.TextField()),
                ('notes_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'chat_session',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='study_notes',
                        to='geography.geographychatsession',
                    ),
                ),
                (
                    'feature',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='study_notes',
                        to='geography.mapfeature',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='study_notes',
                        to='geography.mapproject',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='geography_study_notes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
