# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_geography_ai_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapasset',
            name='board',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mapasset',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mapasset',
            name='subject',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mapfeaturephoto',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
