# Generated by Django 6.0.5 on 2026-05-21 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_profiles', to='simulations.character')),
            ],
            options={
                'ordering': ['world', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DecisionJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_text', models.TextField()),
                ('state_snapshot', models.JSONField(blank=True, default=dict)),
                ('consequences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_journals', to='simulations.simulationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_journals', to=settings.AUTH_USER_MODEL)),
                ('character_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_journals', to='history.historicalcharacterprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('setting', models.JSONField(blank=True, default=dict)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_worlds', to='simulations.scenario')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='historicalcharacterprofile',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_profiles', to='history.historicalworld'),
        ),
        migrations.AddConstraint(
            model_name='historicalworld',
            constraint=models.UniqueConstraint(fields=('scenario', 'slug'), name='unique_historical_world_slug'),
        ),
        migrations.AddConstraint(
            model_name='historicalcharacterprofile',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='unique_historical_profile_slug'),
        ),
    ]
