# Generated by Django 6.0.5 on 2026-05-21 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('negotiation_variables', models.JSONField(blank=True, default=dict)),
                ('documents_required', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_detail', to='simulations.scenario')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('document_type', models.CharField(max_length=80)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_documents', to='simulations.simulationsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_documents', to=settings.AUTH_USER_MODEL)),
                ('business_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='business.businessscenario')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles', to='simulations.role')),
                ('business_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to='business.businessscenario')),
            ],
            options={
                'ordering': ['business_scenario', 'name'],
                'constraints': [models.UniqueConstraint(fields=('business_scenario', 'slug'), name='unique_business_agent_slug')],
            },
        ),
    ]
