# Generated by Django 6.0.5 on 2026-05-21 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('estimated_minutes', models.PositiveIntegerField(default=45)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['simulation_type__order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SimulationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('configuration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('initial_state', models.JSONField(blank=True, default=dict)),
                ('max_players', models.PositiveIntegerField(default=1)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='simulations.scenario')),
            ],
            options={
                'ordering': ['scenario', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('persona', models.JSONField(blank=True, default=dict)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='simulations.role')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='simulations.scenario')),
            ],
            options={
                'ordering': ['scenario', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('current_state', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='simulations.scenario')),
                ('selected_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='simulations.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_sessions', to=settings.AUTH_USER_MODEL)),
                ('simulation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='simulations.simulationtype')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('event_type', models.CharField(max_length=80)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='simulations.character')),
                ('actor_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='simulations.role')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulations.simulationsession')),
            ],
            options={
                'ordering': ['session', 'sequence', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='simulation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='simulations.simulationtype'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('scenario', 'slug'), name='unique_role_slug_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('scenario', 'slug'), name='unique_character_slug_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='simulationevent',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='unique_event_sequence_per_session'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('simulation_type', 'slug'), name='unique_scenario_slug_per_simulation_type'),
        ),
    ]
