# Generated by Django 6.0.5 on 2026-05-21 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentaryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_cases', to='simulations.scenario')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ParliamentaryProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='civics.parliamentarycase')),
            ],
            options={
                'ordering': ['case', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CivicsTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('motion_type', models.CharField(blank=True, max_length=80)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civics_turns', to='simulations.role')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civics_turns', to='simulations.simulationsession')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civics_turns', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='civics.parliamentaryprocedure')),
            ],
            options={
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='parliamentarycase',
            constraint=models.UniqueConstraint(fields=('scenario', 'slug'), name='unique_parliamentary_case_slug'),
        ),
        migrations.AddConstraint(
            model_name='parliamentaryprocedure',
            constraint=models.UniqueConstraint(fields=('case', 'slug'), name='unique_procedure_slug_per_case'),
        ),
        migrations.AddConstraint(
            model_name='civicsturn',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='unique_civics_turn_sequence'),
        ),
    ]
